### ISSUE TITLE
Worng Base/Ending condition

### ISSUE THREAD

**Issue by pulkitent** [pulgupta/ds_algos#1]
https://github.com/pulgupta/ds_algos/blob/f8080bcb58ec1e30471bae5d956e021ec094ad02/src/main/java/org/ds/algos/practice/ds_algos/trees/PathSum.java#L16

The actual condition should be ```sum==0``` rather than ```sum==node.data``` because at each recursive call you are subtracting current node's value from sum.
I am assuming the problem statement to be https://leetcode.com/problems/path-sum/

**Comment by pulgupta** [comment]
Hi, This condition is correct.

Think in this way, what I am doing here is checking if we are at the leaf node. If yes then is the value of the leaf node equal to the sum remaining. For Example
        5->4->1 (Path sum required is 10.)
Say this is my tree. Now I start traversing from the node with value 5. I go to 4 and the sum remaining is 10-5 = 5. I am still not at a leaf so I continue and go to 1. Now the sum remaining is 5-4=1 and I move forward. Now I am at a leaf and so I can compare the sum remaining to the leaf value and if they are same we return true.

**Comment by pulgupta** [comment]
As discussed this is not an issue and is implemented correctly.
